/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr;

/**
 *
 * @author 91788
 */
public class empproject extends javax.swing.JFrame {

    /**
     * Creates new form empproject
     */
    public empproject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("project details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 270, 40);

        jLabel2.setText("Project name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 140, 140, 30);

        jt1.setText("jTextField1");
        getContentPane().add(jt1);
        jt1.setBounds(230, 150, 140, 22);

        jLabel3.setText("client name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 220, 100, 16);

        jt2.setText("jTextField2");
        getContentPane().add(jt2);
        jt2.setBounds(220, 220, 140, 22);

        jLabel4.setText("project type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 290, 160, 16);

        jt3.setText("jTextField3");
        jt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt3ActionPerformed(evt);
            }
        });
        getContentPane().add(jt3);
        jt3.setBounds(220, 290, 120, 22);

        jLabel5.setText("project mangager");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 370, 110, 16);

        jt4.setText("jTextField4");
        getContentPane().add(jt4);
        jt4.setBounds(210, 370, 130, 22);

        jLabel6.setText("developing platform");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 440, 140, 16);

        jt5.setText("jTextField5");
        getContentPane().add(jt5);
        jt5.setBounds(220, 440, 130, 22);

        jLabel7.setText("description");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 500, 130, 16);

        jt6.setText("jTextField6");
        getContentPane().add(jt6);
        jt6.setBounds(220, 500, 150, 22);

        jButton1.setText("get");
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 50, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empproject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    // End of variables declaration//GEN-END:variables
}
