/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr;
import java.awt.Color;
import java.awt.Image;
import java.beans.Statement;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import curtain.call.DBloader;
import java.sql.SQLException;
//import static java.text.MessageFormat.format;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
public class profilee extends javax.swing.JFrame {
 Connection con =null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    ImageIcon format;
    public profilee() {
        initComponents();
        setSize(831,1000);
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        txtusr = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 400, 100, 16);

        jt1.setText("jTextField1");
        getContentPane().add(jt1);
        jt1.setBounds(140, 400, 110, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Email :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 440, 100, 20);

        jt2.setText("jTextField2");
        getContentPane().add(jt2);
        jt2.setBounds(140, 440, 110, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Post :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 490, 100, 25);

        jt3.setText("jTextField3");
        getContentPane().add(jt3);
        jt3.setBounds(140, 490, 110, 22);

        txtusr.setText("jTextField1");
        getContentPane().add(txtusr);
        txtusr.setBounds(200, 90, 160, 22);

        txtpass.setText("jTextField2");
        getContentPane().add(txtpass);
        txtpass.setBounds(200, 150, 160, 22);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 210, 130, 31);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 530, 60, 25);

        jt4.setText("jTextField1");
        getContentPane().add(jt4);
        jt4.setBounds(140, 530, 110, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 580, 70, 25);

        jt5.setText("jTextField2");
        getContentPane().add(jt5);
        jt5.setBounds(140, 580, 110, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Salary :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 710, 80, 30);

        jt6.setText("jTextField3");
        getContentPane().add(jt6);
        jt6.setBounds(110, 720, 110, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Enter Username :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 90, 160, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Enter Password:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 150, 170, 25);

        jl1.setText("jLabel9");
        getContentPane().add(jl1);
        jl1.setBounds(370, 410, 170, 160);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Incremented salary :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 750, 170, 30);

        jt7.setText("jTextField1");
        getContentPane().add(jt7);
        jt7.setBounds(180, 760, 120, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Salary Details");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 640, 270, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Employee Profile");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 320, 310, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Month of increment :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 720, 230, 25);

        jt8.setText("jTextField1");
        getContentPane().add(jt8);
        jt8.setBounds(470, 720, 120, 22);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 710, 10);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 290, 720, 10);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 620, 720, 10);

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 810, 730, 10);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 770, 72, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-3, 0, 2650, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String query= "select * from addemp where username=? and password=?";
        
            try {
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/hr","root","system");
                 pst=con.prepareStatement(query);
        pst.setString(1,txtusr.getText());
         pst.setString(2,txtpass.getText());
         rs=pst.executeQuery();
         if(rs.next()){
              
                    JOptionPane.showMessageDialog(null  ,"login successfully");
                     String namee=rs.getString("name");
                     String postt=rs.getString("post");
                      String idd=rs.getString("id");
                      
                     String emaill=rs.getString("email");
                      String sall=rs.getString("sal");
                     String phonee=rs.getString("phone");
                     String amountt=rs.getString("amount");
                     String monthh=rs.getString("month");
                    // String image;
                    //image = rs.getBlob(7).toString();
                    byte[] image = rs.getBytes("image"); 
                    format = new ImageIcon(image); //this creates an ImageIcon from the bytes array collected from the image in the database.

                Image img = format.getImage(); //this creates an Image, this would be used to carry out the resizing, as ImageIcon cannot be resized directly with this method.
                Image newimage = img.getScaledInstance(jl1.getWidth(), jl1.getHeight(), Image.SCALE_SMOOTH); // This resizes the Image using size from the label which we have placed in the program earlier.
                ImageIcon images = new ImageIcon(newimage);
               
                     jt1.setText(namee);
                     jt2.setText(emaill);
                     jt3.setText(postt);
                     jt4.setText(idd);
                     jt5.setText(phonee);
                     jt6.setText(sall);
                     jt7.setText(amountt);
                     jt8.setText(monthh);
                     jl1.setIcon(images);
                     
                     
         }
         //String querry="select name,post from addemp";
         
         else{
              
                    JOptionPane.showMessageDialog(null  ,"username password do not match");
         }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        emptasks obj=new emptasks();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profilee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profilee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profilee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profilee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profilee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jl1;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtusr;
    // End of variables declaration//GEN-END:variables
}
