/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr;

//import com.mysql.cj.protocol.Message;
//import com.mysql.cj.x.protobuf.MysqlxSession.Reset;
//import com.mysql.cj.xdevapi.Session;
import com.sun.jdi.connect.Transport;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.mail.Message;
import java.net.InetAddress;
import java.net.Socket;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author 91788
 */
public class sendcode extends javax.swing.JFrame {

    /**
     * Creates new form sendcode
     */
    int randomcode;
    public sendcode() {
        initComponents();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("enter email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 110, 16);

        jLabel2.setText("verify code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 100, 16);

        txtemail.setText("jTextField1");
        getContentPane().add(txtemail);
        txtemail.setBounds(240, 60, 100, 22);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 190, 110, 22);

        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 120, 72, 22);

        txtver.setText("Verify");
        txtver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtverActionPerformed(evt);
            }
        });
        getContentPane().add(txtver);
        txtver.setBounds(290, 260, 72, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Random rand = new Random();
        randomcode=rand.nextInt(999999);
        String host="smtp.gmail.com";
        String user="arshcse071@gmail.com";
        String pass="@arsh123";
        String to=txtemail.getText();
        String subject="reseting code";
        String message="your reset code is "+randomcode;
        boolean sessionDebug=false;
        Properties pros=System.getProperties();
        pros.put("mail.smtp.starttls.enable",true);
        pros.put("mail.smtp.host","host");
        pros.put("mail.smtp.port",587);
        pros.put("mail.smtp.auth",true);
        pros.put("mail.smtp.starttls.required",true);
      //  java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros, null);
        mailSession.setDebug(sessionDebug);

        Message msg = new MimeMessage(mailSession);

        msg.setFrom(new InternetAddress(user));

        InternetAddress [] address = {new InternetAddress(to)};

        msg.setRecipients(Message.RecipientType.TO, address);

        msg.setSubject(subject);

        msg.setText(message);

        
        javax.mail.Transport transport = mailSession.getTransport("smtp");

        transport.connect(host, user, pass);

        transport.sendMessage(msg, msg.getAllRecipients());

        transport.close();


        JOptionPane.showMessageDialog(null, "code has been send to the email");

}       
        catch(Exception ex){

                JOptionPane.showMessageDialog(rootPane, ex);

                            }


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtverActionPerformed
        // TODO add your handling code here:
        if(Integer.valueOf(txtver.getText())==randomcode){
        reset rs = new reset(txtemail.getText());
        rs.setVisible(true);

        this.setVisible(false);

        }else{

        JOptionPane.showMessageDialog(null, "code do not match");

}

    }//GEN-LAST:event_txtverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sendcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sendcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sendcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sendcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sendcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JButton txtver;
    // End of variables declaration//GEN-END:variables
}
